project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!internal/"

website:
  title: "How-to guides"
  google-analytics: "G-XZ471458FQ"
  navbar:
    logo: logo_white.svg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/epiverse-trace/howto
          - text: Report a Bug
            url:  https://github.com/epiverse-trace/howto/issues
  repo-url: https://github.com/epiverse-trace/howto/
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, epiversetheme.scss]
    css: styles.css
    toc: true

