---
title: "About"
---

## What is a How-to guide?

[How-to guides](https://diataxis.fr/how-to-guides/) are directions that guide the reader through a problem or towards a result. How-to guides are goal-oriented.

A how-to guide is concerned with work - a task or problem, with a practical goal. Maintain focus on that goal.

A how-to guide serves the work of the already-competent user, whom you can assume to know what they want to do, and to be able to follow your instructions correctly.

## Who are these for?

In the creation of these materials, we though in:

-   __Juan__, a Statistician. He supports the data analysis tasks in the outbreak response team of a National Health Agency. He wants quick code solutions reminders for outbreak analytics. [Read more about Juan](https://epiverse-trace.github.io/personas/juan-datero.html).
-   __Patricia__, a PhD student. She has a Master in Epidemiology with a focus on Modelling of Infectious Diseases Dynamics using MATLAB. She wants to translate theory to practice with R. [Read more about Patricia](https://epiverse-trace.github.io/personas/patricia-discoverer.html).
<!-- -   Celina, a Post-doc and fluent R user who needs to keep up-to-date with the latest package developments. -->
- __Danielle__, an Instructor. She develops training materials for her colleagues at the Ministry of Health. She wants to remix content to create specific training materials for public health practitioners like Field epidemiologists and research degree students. [Read more about Danielle](https://epiverse-trace.github.io/personas/danielle-entretrainer.html).

## Design Principles

- Showcase `R` package integration options within the Outbreak analytics ecosystem.
- Provide a ["How-to" guides](https://documentation.divio.com/how-to-guides/) as single point solutions to specific problems.
- Add links to related [Explanation](https://documentation.divio.com/explanation/) documentation.
- Leverage the ecosystem: Facilitate the Accessibility to the Outbreak analytics ecosystem by using the Tidyverse. This provides a consistent and smoother learning experience to users. Aligned with the [datasciencebox design principles](https://datasciencebox.org/01-design-principles.html#leverage-the-ecosystem) and [FAIR principles for software ecosystems](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.15409).
- Show the context (part of the pipeline), ingredients (packages) and steps.
- Add brief interpretation templates.
- Functions, as in package websites, should have [code-link](https://downlit.r-lib.org/) to their [Reference](https://documentation.divio.com/reference/) documentation.
- Provide a "search by keyword" to find what a user needs.
-   Show the `R` code needed to solve Outbreak Analytics [tasks](index.qmd).
-   Show how [Epidemiology `R` packages](https://cran.r-project.org/web/views/Epidemiology.html) are integrated in [pipelines](index.qmd).
-   Help to identify which coding task can be replaced by new `R` packages.
-   Provide various infectious disease scenarios by world regions and data sources.
-   Refer to external learning resources.
-   Refer to a glossary of terms.
-   Refer to good coding practices.
-   Non-invasive package management with [`{renv}`](https://rstudio.github.io/renv/)

## Contributing

Contributions are always welcome!

See our [Contributing guide](https://github.com/epiverse-trace/howto/blob/main/.github/CONTRIBUTING.md) for ways to get started.

Please adhere to this project's [Code of Conduct](https://github.com/epiverse-trace/howto/blob/main/.github/CODE_OF_CONDUCT.md).

## Support

Please see our [Getting help guide](https://github.com/epiverse-trace/howto/blob/main/.github/SUPPORT.md) for support.

## Related projects

-   [epirecipes](http://epirecip.es/epicookbook/)
-   [How To Articles by Posit Support](https://support.posit.co/hc/en-us/categories/200035113-How-To-Articles)
