---
title: "How to extract the serial interval distribution from a systematic review?"
format: 
  html:
    code-link: true
editor: source
editor_options: 
  chunk_output_type: console
date: last-modified
toc: true
toc_float: true
---

## Ingredients

- Use the distribution estimated from the WHO Ebola Response Team in 2015.

## Steps in code

```{r}
#| warning: false

# Load required packages
library(epiparameter)
library(tidyverse)

# Load the library of parameters as an epiparam object
epiparam_all <- epiparam()

# Filter by disease, epi_distribution, region, and year
epiparam_ebola <- epiparam_all %>% 
  filter(str_detect(disease,"Ebola")) %>% 
  filter(epi_distribution == "serial_interval") %>% 
  filter(region == "West Africa") %>% 
  filter(year == 2015)

epiparam_ebola

# Convert a row to an epidist class object
epidist_ebola <- as_epidist(epiparam_ebola)

epidist_ebola

# Plot the epidist object
plot(epidist_ebola,day_range = 0:50)
```

## Steps in detail

- The `epiparameter` package is loaded to access the library of epidemiological parameters.
- The `epidist_db()` function extract a parameter by specifying the disease name in the `disease` argument, epidemiological distribution in the `epi_dist` argument, and author name in the `author` argument.
- The `epidist_db()` function creates an `epidist` object.
- The `plot` function creates a plot from `epidist` objects. 
- The `epiparam()` functions provide access to a data frame with all the names of diseases, epidemiological distribution, and authors.

Please note that the code assumes the necessary packages are already installed. If they are not, you can install them using first the `install.packages("pak")` function and then the `pak::pak()` function for both packages in CRAN or GitHub before loading them with `library()`. 

Additionally, make sure to adjust the serial interval distribution parameters according to the specific outbreak you are analyzing.

## Related

- [Explanation on epidemiological distributions](https://www.reconlearn.org/slides/outbreak-statistics/outbreak-statistics.html#14)
